### ISSUE TITLE
`pyrfuniverse` referenced in installation instructions

### ISSUE THREAD

**Issue by tomsilver** [empriselab/RCareWorld#10]
Hello, thanks for your work on this awesome project!

Just a small note: `pyrfuniverse` and `pyrfuniverse_rcare` are referenced in [the installation instructions](https://sunny-building-1e7.notion.site/Install-the-Modules-014832fa7896462893ce332cf8e70a7f), but I believe these were [recently removed](https://github.com/empriselab/RCareWorld/commit/8f54db48ae1e664c9967961d0c22f2c434466c15).

**Comment by YoruCathy** [comment]
Thanks for the catch! Fixed it.
