### ISSUE TITLE
`SetJointVelocity` seems to set position instead of velocity

### ISSUE THREAD

**Issue by thisjustin123** [empriselab/RCareWorld#135]
## Description

`SetJointVelocity` is allegedly setting a joint position (or has the effect of doing so) rather than a velocity. Quote:

>Regarding https://github.com/empriselab/RCareWorld/blob/bcefa67b79bfb7e64e2bd07b1ce2512988973766/template/test_bathing.py#L81-L83, why does 'applying' the `SetJointVelocity` command for e.g. 400 steps does not make a difference? When I change the commanded 'velocity' from -0.5 to -1, the respective joint extends further. Still, it behaves as I would expect from position control and not from velocity control. Am I misunderstanding something there?

**Comment by thisjustin123** [comment]
Figured out why this is happening, I'm pretty sure. 

In Unity, we are using ArticulationBody components, which can take both a target position and velocity. When just a target velocity is set, the component still takes into account the target position, which can result in an equilibrium position in which the target postion and velocity are cancelling each other out.

Will look into an alternative.

**Comment by thisjustin123** [comment]
It might actually be better to inform people of this and perhaps optionally provide a "set drive type" function to assist people setting Stiffness and Damping to get around this. That's what Unity does.

**Comment by thisjustin123** [comment]
Update: Toyed around with things, and I can't seem to find any parameters that I can change to achieve a very clean, no-movement joint velocity match. Damping doesn't seem to make any difference past some point and the robot keeps drifting. Doesn't look too promising.

**Comment by YoruCathy** [comment]
There isn't a solution for velocity control of prismatic joints, limited by Unity's physics backend. Users should avoid using it for now.
