### ISSUE TITLE
OMPL Support Not Working as Expected

### ISSUE THREAD

**Issue by thisjustin123** [empriselab/RCareWorld#143]
## Description:

A user has described the following issue when trying to use OMPL:

`"When we use the example_ompl.py script, we receive a continuous error message stating "An Error Occurred: OmplManagerAttr".`

It seems this is the source of the error message:

![image](https://github.com/user-attachments/assets/05e049f0-ce04-416a-bd15-dec8c30c817f)

Inspecting the attribute mapping code, we see that OMPLManager is commented out, meaning it indeed should not work:

![image](https://github.com/user-attachments/assets/552596d0-e0a0-44d9-aaaf-e9091a654283)

**Comment by ALaws0n** [comment]
During my attempt to investigate this issue, I made sure that line was uncommented in the attribute mappings. The error occurs even after fixing that.

**Comment by YoruCathy** [comment]
Resolved in #144
