### ISSUE TITLE
OMPL is causing failures if not installed

### ISSUE THREAD

**Issue by thisjustin123** [empriselab/RCareWorld#177]
## Description:

OMPL must now be installed to run any scene or RCareWorld file, and otherwise causes a crash.

To anyone experiencing this issue, run this command in your terminal. This is a temporary fix (and will install ompl on your computer):

`python3 -m pip install https://github.com/ompl/ompl/releases/download/prerelease/ompl-1.6.0-cp310-cp310-manylinux_2_28_x86_64.whl`

WARNING: Only make sure to install this if you don't have any other versions of OMPL installed!

**Comment by YoruCathy** [comment]
Merged the PR.
