### ISSUE TITLE
The namespace <global namespace> already contains a definition 

### ISSUE THREAD

**Issue by kavikode** [empriselab/RCareWorld#21]
please help me fix the following…
![unityerror](https://github.com/empriselab/RCareWorld/assets/29847048/45e38479-a4b6-4bae-b26e-b1b6edb08de7)
The namespace <global namespace> already contains a definition  error

**Comment by YoruCathy** [comment]
Deleting the `Extend/Digit` folder should be the easiest way to fix this if you don't need anything from that folder.

**Comment by kavikode** [comment]
thank you @YoruCathy it seems to go forward
