### ISSUE TITLE
BioIK does not contain a definition

### ISSUE THREAD

**Issue by kavikode** [empriselab/RCareWorld#22]
Will you please help me resolve the following errors?
1. Assets\RCareWorld\Scripts\Attributes\ControllerAttr.cs(423,19): error CS1061: 'BioIK' does not contain a definition for 'isArticulations' and no accessible extension method 'isArticulations' accepting a first argument of type 'BioIK' could be found (are you missing a using directive or an assembly reference?)
2. Assets\RCareWorld\Scripts\Attributes\ControllerAttr.cs(613,27): error CS1061: 'BioIK' does not contain a definition for 'FixedUpdate1' and no accessible extension method 'FixedUpdate1' accepting a first argument of type 'BioIK' could be found (are you missing a using directive or an assembly reference?)
3. Assets\RCareWorld\Scripts\Attributes\ControllerAttr.cs(614,48): error CS1061: 'BioIK' does not contain a definition for 'targets' and no accessible extension method 'targets' accepting a first argument of type 'BioIK' could be found (are you missing a using directive or an assembly reference?)
4. Assets\RCareWorld\Scripts\Attributes\ControllerAttr.cs(1071,23): error CS1061: 'BioIK' does not contain a definition for 'FixedUpdate1' and no accessible extension method 'FixedUpdate1' accepting a first argument of type 'BioIK' could be found (are you missing a using directive or an assembly reference?)
5. Assets\RCareWorld\Scripts\Attributes\ControllerAttr.cs(1073,40): error CS1061: 'BioIK' does not contain a definition for 'targets' and no accessible extension method 'targets' accepting a first argument of type 'BioIK' could be found (are you missing a using directive or an assembly reference?)

**Comment by YoruCathy** [comment]
Hi, could you confirm that you have BioIK in your package manager?

**Comment by kavikode** [comment]
Yes, I have BioIK in your package manager

**Comment by kavikode** [comment]
yes, I confirm

**Comment by sanfeed** [comment]
I get the same error. I try to search "isArticulations" in the BioIK and result is empty. The BioIK version is 2.0d.

**Comment by jinwuzi** [comment]
I get the same error. Assets\RFUniverse\Runtime\Scripts\Attributes\ControllerAttr.cs(268,19): error CS1061: 'BioIK' does not contain a definition for 'isArticulations' and no accessible extension method 'isArticulations' accepting a first argument of type 'BioIK' could be found (are you missing a using directive or an assembly reference?)
