### ISSUE TITLE
Couldn't connect to trainer on port 5004 using API version 1.5.0

### ISSUE THREAD

**Issue by kavikode** [empriselab/RCareWorld#24]
I opened the Empty.unity in Assets/RCareWorld/Scenes by double clicking on the logo of the scene. 
I clicked on the play button, but I received the following message:

"Couldn't connect to trainer on port 5004 using API version 1.5.0" 

what is the best way to resolve this issue?
Thank you

**Comment by YoruCathy** [comment]
Hi, you'll need to run python script first before clicking the `Run` button in Unity.

**Comment by kavikode** [comment]
which Python script specifically? Thank you
