### ISSUE TITLE
OpenCV-contrib issues

### ISSUE THREAD

**Issue by kavikode** [empriselab/RCareWorld#26]
When I run "python Examples/example_base_object.py" I received a message that "opencv-contrib not installed, some features will be disabled. Please install with `pip3 install opencv-contrib-python"

To resolve it, I did the following:
pip install opencv-python==4.5.4.60
pip install opencv-contrib-python==4.5.4.60

I received the following messages:
Requirement already satisfied: opencv-python==4.5.4.60 in c:\users\kavita\desktop\rcareworld_workspace\venv\lib\site-packages (4.5.4.60)
Requirement already satisfied: numpy>=1.17.3 in c:\users\kavita\desktop\rcareworld_workspace\venv\lib\site-packages (from opencv-python==4.5.4.60) (1.24.2)

Requirement already satisfied: opencv-contrib-python==4.5.4.60 in c:\users\kavita\desktop\rcareworld_workspace\venv\lib\site-packages (4.5.4.60)
Requirement already satisfied: numpy>=1.17.3 in c:\users\kavita\desktop\rcareworld_workspace\venv\lib\site-packages (from opencv-contrib-python==4.5.4.60) (1.24.2)

How can I best resolve this?

Thank you for your assistance

**Comment by YoruCathy** [comment]
Hi @kavikode , I'm not entirely sure why this happens but you can probably try installing other versions of opencv python and see if it works. If not, we have a docker image for conda environment that you can use https://hub.docker.com/repository/docker/cathyye2000/rcareworld/general
Hopefully this will address the issue.

**Comment by kavikode** [comment]
thank you so much
