### ISSUE TITLE
Missing Prefab

### ISSUE THREAD

**Issue by kavikode** [empriselab/RCareWorld#29]
I am unable to click and drag the female1_cp CareAvatar prefab from the folder Assets/RCareWorld/Assets/Prefabs/CareAvatars/WithWheelchair into the CareAvatarAnime scene 

I received the message: Prefab instance problem. Missing Prefab Asset: 'female1_cp (Missing Prefab with guid: c505147a5e39baad2a97dea0ec291164)'
UnityEditor.EditorApplication:Internal_RestoreLastOpenedScenes ()

Can you please provide a way to resolve this issue?

**Comment by YoruCathy** [comment]
Could you take a screenshot of the folder Assets/RCareWorld/Assets/Prefabs/CareAvatars/WithWheelchair? How do the icons looks like?

**Comment by kavikode** [comment]
yes please see the following the following screenshot
![missing prefab](https://github.com/empriselab/RCareWorld/assets/29847048/4d5f0dcb-2b9e-477d-b27c-ad74cb0a1798)

**Comment by kavikode** [comment]
thank you @YoruCathy

**Comment by YoruCathy** [comment]
Seems the link from prefab to model is somehow lost.. Are the Avatars under WithoutWheelchair folder normal?

**Comment by kavikode** [comment]
I can see the icons are thumbnails for the items inside. here is the screenshot:
![UnityWithout Normal](https://github.com/empriselab/RCareWorld/assets/29847048/c2fef3f4-3ae9-4647-af62-0aac5b2aca2e)

What is the best method to fix this issue please?

**Comment by YoruCathy** [comment]
I guess the link to the wheelchair is somehow broken when the project is being imported. I'll send you the prefab soon.

**Comment by kavikode** [comment]
thank you so much! please let me know when it is ready

**Comment by kavikode** [comment]
just trying to follow up on this issue. Thank you

**Comment by YoruCathy** [comment]
This is deprecated.
