### ISSUE TITLE
Install the modules page is missing a directive to install CPP build tools

### ISSUE THREAD

**Issue by mdear-lsn** [empriselab/RCareWorld#5]
https://sunny-building-1e7.notion.site/Install-the-Modules-51be8ddaf4404cd196a90ecde47a081e

is missing a reference to (when installing on a Windows system, as is the case for my son's Tobii I13 voice prosthetic eye tracking device on which I intend to integrate RCareWorld) : 

https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by YoruCathy** [comment]
Thanks for the suggestion. We'll add it to the instructions.
