### ISSUE TITLE
Port 5004

### ISSUE THREAD

**Issue by kavikode** [empriselab/RCareWorld#68]
Even though I have added the inbound rule on port 5004 on Windows 10,  I tried to run the following Example Scenes and I received the associated errors listed below. Will you please help me to resolve them?

1. Ambulating-L3.unity
* Couldn't connect to trainer on port 5004 using API version 1.5.0. Will perform inference instead.
UnityEngine.Debug:Log (object)
* Rigister ID:3158930 Name:robotiq_arg2f_85_model
* Rigister ID:315893 Name:kinova_gen3_7dof-robotiq85

2. Limb Reposition.unity
* left_wrist: The referenced script (Unknown) on this Behaviour is missing! 
* left_shoulder: The referenced script (Unknown) on this Behaviour is missing! 
* left_wrist: The referenced script (Unknown) on this Behaviour is missing! 
* Couldn't connect to trainer on port 5004 using API version 1.5.0. Will perform inference instead.
* Rigister ID:35987 Name:kinova_gen3
* Rigister ID:197453 Name:hand_point
* Rigister ID:197454 Name:Target
* Rigister ID:36000 Name:SMPLX-male
* Rigister ID:2657 Name:limb_tool
* Rigister ID:359870 Name:grasp_point

Thank you!

**Comment by YoruCathy** [comment]
HI Kavita, could you explain more about what you did and get the errors? The general rule is to run python script and then click the run button on Unity.

**Comment by YoruCathy** [comment]
One thing you can test if the connection of Python and Unity is successful is to use the executables here: https://github.com/empriselab/RCareWorld/tree/cornell-hackathon

**Comment by kavikode** [comment]
Thank you so much @YoruCathy ! Which branch would be the best to use at this point with the latest zip file that was sent with the Unity project? I will try it after I hear from you

**Comment by YoruCathy** [comment]
Both the main branch and cornell-hackathon work. The cornell-hackathon one has executable files you can use to test if the python installation is successful.

**Comment by kavikode** [comment]
thank you for your reply.
1. Which python file is associated with the scene Limb Reposition because the kinova_gen3 robotic arm is not moving and the human arm just drops down after clicking on the play button within Unity? 

2. In the Bed Bathing Unity scene, the HiPoly Hospital Bed Variant is not visible even though I dragged the prefab from Devices Folder? There's also no movement other than the arms dropping after the play button is clicked.

**Comment by YoruCathy** [comment]
This is deprecated.
